ALLOWED_OWNERS = ("aaronedev", "Violet-Void", "bauerstischfinder")
PROFILE_REPO = "aaronedev/aaronedev"
PR_LIMIT = 8
CONTRIB_LIMIT = 10
CONTRIB_REPO_LIMIT = 100
ACTIVITY_START = "<!--START_SECTION:activity-->"
ACTIVITY_END = "<!--END_SECTION:activity-->"
WAKA_START = "<!--START_SECTION:waka-->"
WAKA_END = "<!--END_SECTION:waka-->"
PROFILE_START = "<!--START_SECTION:profile-->"
PROFILE_END = "<!--END_SECTION:profile-->"
AUTHOR_LOGIN = "aaronedev"
PROFILE_TIMEZONE = "Europe/Berlin"
MAX_PR_PAGES = 100
MAX_HISTORY_PAGES = 100
PAGE_SIZE = 100
