---
name: Update README
on:
  push:
    branches: [main]
  schedule:
  - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch: # allow manual trigger

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: muesli/readme-scribe@master
      env:
        GITHUB_TOKEN: ${{ secrets.PROFILE_WORKFLOW }}
      with:
        template: README.md.tpl
        writeTo: README.md

    - uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.PROFILE_WORKFLOW }}
        SHOW_LINES_OF_CODE: "True"
        SHOW_PROFILE_VIEWS: "False"
        SHOW_COMMIT: "True"
        SHOW_DAYS_OF_WEEK: "True"
        SHOW_LANGUAGE: "True"
        SHOW_OS: "True"
        SHOW_PROJECTS: "True"
        SHOW_TIMEZONE: "False"
        SHOW_EDITORS: "True"
        SHOW_LANGUAGE_PER_REPO: "True"
        SHOW_SHORT_INFO: "False"
        SHOW_LOC_CHART: "False"

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update generated README
        branch: main
